# TODO delete un-used params
defaults:
  - hydra/job_logging: disabled
  - hydra/output_subdir: null
hydra:
  output_subdir: null
  run:
    dir: logs/hydra
main:
  experiment_name_prefix: my_exp
  seed: 1
  num_workers: 5
  parallel: False
  gpus_to_use: 1,2
  trains: False
  paths:
    base_path: '/datashare'
    logs: 'logs/'
    processed_imgs: './resnet-14x14.h5'
    vocab_path: './vocab_updated.json'
  train_paths:
    questions: 'v2_OpenEnded_mscoco_train2014_questions.json'
    answers: 'v2_mscoco_train2014_annotations.json'
    imgs: 'train2014'
  val_paths:
    questions: 'v2_OpenEnded_mscoco_val2014_questions.json'
    answers: 'v2_mscoco_val2014_annotations.json'
    imgs: 'val2014'
train:
  question_features: 1024
  image_features: 110 # TODO make sure code can handle dim change
  classifier_hidden_dim: 1024
  attention_hidden_dim: 512
  glimpses: 2
  max_answers: 3000
  embedding_features: 300
  image_size: 32 # TODO increase!!! # scale shorter end of image to this size and centre crop
  central_fraction: 0.875  # only take this much of the centre when scaling and centre cropping
  dropouts:
    text: 0.5
    attention: 0.5
    classifier: 0.5
  num_epochs: 10
  grad_clip: 0.25
  num_hid: 20
  batch_size: 16
  save_model: True
  lr:
    lr_value: 1e-3
    lr_decay: 15
    lr_gamma: 0.1
    lr_step_size: 30